export default {
  INCREASE: "INCREASE",
  SET_USER_NAME: "SET_USER_NAME",
  PING: "PING",
  PONG: "PONG",
  FETCH_POKEMONS: "FETCH_POKEMONS",
  FETCH_POKEMONS_FULFILLED: "FETCH_POKEMONS_FULFILLED",
  FETCH_POKEMON: "FETCH_POKEMON",
  FETCH_POKEMON_FULFILLED: "FETCH_POKEMON_FULFILLED"
};
