export default {
  INCREASE: "INCREASE",
  SET_USER_NAME: "SET_USER_NAME",
  PING: "PING",
  PONG: "PONG",
  FETCH_POKEMONS: "POKEAPI/FETCH_POKEMONS",
  FETCH_POKEMONS_FULFILLED: "POKEAPI_RESPONSE/FETCH_POKEMONS_FULFILLED",
  FETCH_POKEMON: "POKEAPI/FETCH_POKEMON",
  FETCH_POKEMON_FULFILLED: "POKEAPI_RESPONSE/FETCH_POKEMON_FULFILLED"
};
