export default {
  INCREASE: "INCREASE",
  SET_USER_NAME: "SET_USER_NAME",
  PING: "PING",
  PONG: "PONG",
  FETCH_REPOSITORIES: "GITHUB/FETCH_REPOSITORIES",
  FETCH_REPOSITORIES_NEXT_PAGE: "GITHUB/FETCH_REPOSITORIES_NEXT_PAGE",
  FETCH_REPOSITORY: "GITHUB/FETCH_REPOSITORY",
  FETCH_REPOSITORIES_FULFILLED: "GITHUB_RESPONSE/FETCH_REPOSITORIES_FULFILLED",
  FETCH_REPOSITORY_FULFILLED: "GITHUB_RESPONSE/FETCH_REPOSITORY_FULFILLED",
  FETCH_POKEMONS: "POKEAPI/FETCH_POKEMONS",
  FETCH_POKEMONS_FULFILLED: "POKEAPI_RESPONSE/FETCH_POKEMONS_FULFILLED",
  FETCH_POKEMON: "POKEAPI/FETCH_POKEMON",
  FETCH_POKEMON_FULFILLED: "POKEAPI_RESPONSE/FETCH_POKEMON_FULFILLED"
};
